name: Bug Report
description: Bugs in the software itself
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: Have you tried **ALL THE STEPS** in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting) already?
        required: true
      - label: Have you already **searched** for your issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=)?
        required: true
- type: textarea
  attributes: 
    label: Describe the Bug
    description: 💥 What's the bug?
  validations:
    required: true
    
- type: textarea
  attributes: 
    label: To Reproduce 
    description: 🧙 How can we emulate the bug on our own machine? (Please write in steps)
  validations:
    required: true

- type: input
  attributes:
    label: Upscayl Version (or commit hash)
    description: ✍️ What version of Upscayl did you use?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Platform
    description: 🧑‍💻 What operating system or distribution platform do you use? Select the last one that applies.
    options:
      - Linux
      - Mac App Store
      - MacOS DMG / Homebrew
      - Flatpak
      - Windows
  validations:
    required: true

- type: input
  attributes:
    label: OS Version
    description: "✍️ What's the version of your operating system? (Example: Ubuntu 22.04, MacOS Monterey or Windows 10)"
  validations:
    required: true

- type: input
  attributes:
    label: GPU Name
    description: 📝 What GPU do you have? If you do not know, please just write your device name if it's a laptop. If the name is something like "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq). 
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behavior (OPTIONAL)
    description: 🤓 What should've happened?
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Screenshots (OPTIONAL)
    description: 🤳 Got screenshots?

- type: textarea
  attributes: 
    label: Paste the logs
    description: 💥 Paste the logs below. ([Here's a Guide if you don't know how to do that](https://github.com/upscayl/upscayl/wiki/Guide#logs))
    render: sh
  validations:
    required: true
